### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by stef0296** [tempmail-lol/server#8]
The SSL handshake fails when trying to access https://api.tempmail.lol/
As a result, it is impossible to create or access inboxes via API.
<img width="1512" alt="Screenshot 2023-10-06 at 16 53 08" src="https://github.com/tempmail-lol/server/assets/19484922/bad1358f-7703-420b-9b00-63d67314c3ba">

**Comment by Lefeus** [comment]
![image](https://github.com/tempmail-lol/server/assets/111588764/794efb5a-71fe-4606-96a9-5df9fb0ddd83)

**Comment by AlexanderEpolite** [comment]
Sorry for the issues with this.

The server has been hit with a lot more traffic than usual, and might be under a DDoS attack as well.  Version 2 of the API is coming out soon and will fix this issue.

**Comment by AlexanderEpolite** [comment]
Fixed in v2
